export default {
    MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
    MARK_NOTIFICATION_AS_ALLREAD: 'MARK_NOTIFICATION_AS_ALLREAD',
    START_FETCH_NOTIFICATION: 'START_FETCH_NOTIFICATION',
    FINISH_FETCH_NOTIFICATION: 'FINISH_FETCH_NOTIFICATION',
    RECIVDE_NOTIFIACTION: 'RECIVDE_NOTIFIACTION'
}